# Generated by Django 2.2.5 on 2019-09-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Thread')),
            ],
        ),
    ]
